package com.mds.passkit.constants;



/**
 * Created by mradul on 07/03/16.
 */
public interface PasskitConstants {

    public interface Keys {
        String LOGO_TEXT = "PASS.LOGO_TEXT";
        String DESCRIPTION = "PASS.DESCRIPTION";
        String ORGANIZATION_NAME = "PASS.ORGANIZATION_NAME";
        String PASS_TYPE_IDENTIFIER ="PASS.PASS_TYPE_IDENTIFIER";
        String TEAM_IDENTIFIER = "PASS.TEAM_IDENTIFIER";
        String RESOURCE_LOCATION_PATH = "PASS.RESOURCE_LOCATION_PATH";
        String P12_CERTIFICATE_FILE_PATH = "PASS.P12_CERTIFICATE_FILE_PATH";
        String P12_CERTIFICATE_PASSWORD = "PASS.P12_CERTIFICATE_PASSWORD";
        String P12_CERTIFICATE_ALIAS = "PASS.P12_CERTIFICATE_ALIAS";
        String APPLE_WWDRCA_FILE_PATH = "PASS.APPLE_WWDRCA_FILE_PATH";
        String WEB_SERVICE_URL = "PASS.WEB_SERVICE_URL";

    }
}
